export const FETCH_DEFAULT_DATA_REQUEST = "FETCH_DEFAULT_DATA_REQUEST";
export const FETCH_DEFAULT_DATA_SUCCESS = "FETCH_DEFAULT_DATA_SUCCESS";
export const FETCH_DEFAULT_DATA_FAILURE = "FETCH_DEFAULT_DATA_FAILURE";

export const FETCH_DATA_BY_SEARCH_REQUEST = "FETCH_DATA_BY_SEARCH_REQUEST";
export const FETCH_DATA_BY_SEARCH_SUCCESS = "FETCH_DATA_BY_SEARCH_SUCCESS";
export const FETCH_DATA_BY_SEARCH_FAILURE = "FETCH_DATA_BY_SEARCH_FAILURE";
export const FETCH_DATA_BY_SEARCH_FAILURE_FOR_NO_CITY = "FETCH_DATA_BY_SEARCH_FAILURE_FOR_NO_CITY";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";

export const UNLIKE_REQUEST = "UNLIKE_REQUEST";
export const UNLIKE_SUCCESS = "UNLIKE_SUCCESS";
export const UNLIKE_FAILURE = "UNLIKE_FAILURE";

export const FETCH_LIKED_CITIES_DATA_REQUEST =
  "FETCH_LIKED_CITIES_DATA_REQUEST";
export const FETCH_LIKED_CITIES_DATA_SUCCESS =
  "FETCH_LIKED_CITIES_DATA_SUCCESS";
export const FETCH_LIKED_CITIES_DATA_FAILURE =
  "FETCH_LIKED_CITIES_DATA_FAILURE";

export const key = `XDDsvcihzssshzX6DGzEaRuN3EWllumk`;
